import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createFetcher,discoverLinks,assertURL,checkSources} from '../pipeline/retrieval.mjs';
test('unknown domains and unsafe protocols rejected',()=>{for(const url of ['http://example.org','https://127.0.0.1/','https://example.org:123/','https://u:p@example.org/']) assert.throws(()=>assertURL(url,['example.org']));});
test('fixture link discovery flags new firms without trusting their content',()=>{const list=discoverLinks('<a href="https://new-pollster.example/quebec-poll">New Québec poll</a><a href="javascript:alert(1)">poll</a>','https://qc125.com/',{id:'qc125'});assert.equal(list.length,1);assert.equal(list[0].kind,'new-source-candidate');});
test('robots restrictions prevent target request',async()=>{const calls=[];const f=createFetcher({spacing:0,fetchImpl:async u=>{calls.push(u);return new Response('User-agent: *\nDisallow: /poll');}});await assert.rejects(()=>f('https://example.org/poll',['example.org']),/robots/);assert.equal(calls.length,1);});
test('redirect host must be explicitly approved',async()=>{const f=createFetcher({spacing:0,fetchImpl:async u=>u.endsWith('robots.txt')?new Response('User-agent: *\nAllow: /'):new Response('',{status:302,headers:{location:'https://unknown.example/poll'}})});await assert.rejects(()=>f('https://example.org/poll',['example.org']),/Unapproved/);});
test('robots redirects are bounded and do not recursively reload policy',async()=>{let calls=0;const f=createFetcher({spacing:0,fetchImpl:async()=>{calls++;return new Response('',{status:302,headers:{location:'/robots.txt'}});}});await assert.rejects(()=>f('https://example.org/poll',['example.org']),/Too many redirects/);assert.equal(calls,5);});
test('failed source leaves prior events and successful timestamp intact',async()=>{const s={events:[{id:'accepted'}],reviews:[],discoveries:[],health:[{url:'https://example.org/',lastSuccessAt:'2026-09-01'}]};await checkSources(s,{fetcher:async()=>{throw new Error('HTTP 503');},registry:[{id:'fixture',enabled:true,urls:['https://example.org/'],hosts:['example.org']}],now:'2026-09-12'});assert.equal(s.events.length,1);assert.equal(s.health[0].status,'failed');assert.equal(s.health[0].lastSuccessAt,'2026-09-01');});
